# Generated by Django 3.2.5 on 2021-08-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='pretime',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='createname',
            field=models.CharField(max_length=200, null=True, verbose_name='预约人'),
        ),
    ]
