# Generated by Django 3.2.5 on 2021-07-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('people', models.CharField(max_length=100)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('createname', models.CharField(max_length=200)),
                ('pretime', models.CharField(max_length=100)),
            ],
        ),
    ]
