# Generated by Django 3.2.5 on 2021-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0002_meetings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='createname',
            field=models.CharField(max_length=200, verbose_name='预约人'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='endtime',
            field=models.CharField(max_length=200, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='name',
            field=models.CharField(max_length=200, verbose_name='会议室名称'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='people',
            field=models.CharField(max_length=100, verbose_name='容纳人数'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='pretime',
            field=models.CharField(max_length=100, verbose_name='会议持续时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starttime',
            field=models.CharField(max_length=200, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=200, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=200, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='truename',
            field=models.CharField(max_length=200, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=200, verbose_name='用户名'),
        ),
    ]
