# Generated by Django 3.2.5 on 2021-08-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0002_auto_20210810_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
    ]
