# Generated by Django 3.2.5 on 2021-07-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0006_auto_20210730_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='createname',
            field=models.CharField(max_length=200, null=True, verbose_name='预约人'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='endtime',
            field=models.CharField(max_length=200, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='pretime',
            field=models.CharField(max_length=100, null=True, verbose_name='会议持续时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starttime',
            field=models.CharField(max_length=200, null=True, verbose_name='开始时间'),
        ),
    ]
