# Generated by Django 3.2.5 on 2021-08-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0007_auto_20210730_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['username'], 'verbose_name': '员工信息', 'verbose_name_plural': '员工信息'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='lastlogintime',
            field=models.DateTimeField(null=True, verbose_name='上次登录时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='createname',
            field=models.DateTimeField(null=True, verbose_name='预约人'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='endtime',
            field=models.DateTimeField(null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='pretime',
            field=models.DateTimeField(null=True, verbose_name='会议持续时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starttime',
            field=models.DateTimeField(null=True, verbose_name='开始时间'),
        ),
    ]
