# Generated by Django 3.2.5 on 2021-08-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0009_auto_20210804_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='endtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='pretime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='会议持续时间'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='starttime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='lastlogintime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='上次登录时间'),
        ),
    ]
