# Generated by Django 3.2.5 on 2021-08-05 11:06

import django.contrib.auth.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('yuding', '0011_auto_20210804_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usertype', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=200, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='密码')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='邮箱')),
                ('realname', models.CharField(db_index=True, max_length=200, verbose_name='真实姓名')),
                ('lastlogintime', models.DateTimeField(auto_now=True, null=True, verbose_name='上次登录时间')),
                ('gender', models.CharField(choices=[('men', '男'), ('women', '女')], max_length=300)),
                ('department', models.CharField(choices=[('tech', '技术部'), ('xingzheng', '行政部')], max_length=300)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'by_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
