# Generated by Django 3.2.5 on 2021-08-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0012_auto_20210805_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, null=True, verbose_name='密码')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='邮箱')),
                ('realname', models.CharField(db_index=True, max_length=200, verbose_name='真实姓名')),
                ('lastlogintime', models.DateTimeField(auto_now=True, verbose_name='上次登录时间')),
                ('mod_data', models.DateTimeField(auto_now=True, verbose_name='最近修改时间')),
                ('gender', models.CharField(choices=[('men', '男'), ('women', '女')], max_length=300)),
                ('department', models.CharField(choices=[('tech', '技术部'), ('xingzheng', '行政部')], max_length=300)),
            ],
            options={
                'verbose_name': '员工信息',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
