# Generated by Django 3.2.5 on 2021-08-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuding', '0013_auto_20210807_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name='用户名'),
        ),
    ]
