# Generated by Django 3.2.5 on 2021-08-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': '用户信息'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='department',
            field=models.CharField(choices=[('jishu', '技术部'), ('xingzheng', '行政部')], default='jishu', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='fullname',
            field=models.CharField(max_length=200, null=True, verbose_name='全名'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=200, null=True, verbose_name='用户名'),
        ),
    ]
