# Generated by Django 3.2.5 on 2021-08-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210809_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='identifier',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
