# Generated by Django 3.2.5 on 2021-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='identifier',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=2, max_length=200, unique=True, verbose_name='用户名'),
            preserve_default=False,
        ),
    ]
