# Generated by Django 3.2.5 on 2021-08-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(choices=[('jishu', '技术部'), ('xingzheng', '行政部')], default='技术部', max_length=10),
        ),
    ]
